apiVersion: v1
kind: Secret
metadata:
  name: arangodb
  labels:
    app: {{ include "microservice.name" . }}
type: Opaque
data:
  DBUserName: {{ default "root" .Values.arango.username | b64enc | quote }}
  DBPassword: {{ default "" .Values.arango.password | b64enc | quote }}
  DBHost:     {{ default "localhost" .Values.arango.host | b64enc | quote }}
  DBPort:     {{ default "8529" .Values.arango.port | b64enc | quote }}
---