---
apiVersion: v2
description: Post-Deployment Vulnerability Detection Backend
icon: https://ortelius.github.io/ortelius-charts/logo.png
name: pdvd-backend
type: application
version: 12.0.0
appVersion: 12.0.0
